import type { Plugin, ViteDevServer } from "vite";
import { promises as fs } from "node:fs";
import path from "node:path";
import type BBImage from "../../src/components/common/bbImage.component";

interface ImagePathPluginOptions {
  assetsPath?: string;
  outputDir?: string;
  outputClientDir?: string;
  includeDirs?: string[];
  debug?: boolean;
}

function defaultOptions(): Required<ImagePathPluginOptions> {
  return {
    assetsPath: "public",
    outputDir: "build",
    outputClientDir: "build/client/assets",
    includeDirs: ["images", "themes"],
    debug: false,
  };
}

async function walk(dir: string): Promise<string[]> {
  const entries = await fs
    .readdir(dir, { withFileTypes: true })
    .catch(() => []);
  const files = await Promise.all(
    entries.map((entry) => {
      const fullPath = path.join(dir, entry.name);
      return entry.isDirectory() ? walk(fullPath) : fullPath;
    }),
  );
  return files.flat();
}

function toPascalCase(input: string): string {
  return (
    input.replace(/(^\w|-\w|_\w)/g, (m) =>
      m.replace(/[-_]/, "").toUpperCase(),
    ) + "Path"
  );
}

async function generateTypeFile(options: Required<ImagePathPluginOptions>) {
  const assetsAbsPath = path.resolve(process.cwd(), options.assetsPath);
  const outputPath = path.resolve(
    process.cwd(),
    `${options.outputDir}/types/image-paths.d.ts`,
  );
  const outputDir = path.dirname(outputPath);

  await fs.mkdir(outputDir, { recursive: true });

  const typeBlocks: string[] = [];

  for (const subDir of options.includeDirs) {
    const fullDir = path.join(assetsAbsPath, subDir);
    const files = await walk(fullDir);
    const relativeFiles = files.map((file) =>
      path.relative(assetsAbsPath, file).replace(/\\/g, "/"),
    );

    const typeName = toPascalCase(subDir); // e.g., ImagePath, ThemePath
    const literals =
      relativeFiles.map((f) => `"${f}"`).join(" |\n    ") || "never";

    // FIXME: #112 fix: add support for scanning assets(images, videos, etc.) in sub-directories to inject width/height attributes so BBImage can render the fallback at the correct size

    typeBlocks.push(`  export type ${typeName} =\n    ${literals};`);
  }

  const newBlock = `
// --- GENERATED BY vite-plugin-generate-image-paths ---
declare global {
${typeBlocks.join("\n\n")}
}

export {};
// --- END GENERATED BY vite-plugin-generate-image-paths ---
`.trim();

  await fs.writeFile(outputPath, newBlock + "\n", "utf-8");
  if (options.debug)
    console.debug(
      `[vite-plugin-generate-image-paths] Wrote: ${options.outputDir}`,
    );
}

/**
 * Vite plugin that generates TypeScript type definitions for asset paths in your project.
 *
 * This plugin scans specified directories within your assets folder and generates
 * type-safe path definitions (e.g., `ImagePath`, `ThemePath`) that can be used with
 * the {@link BBImage} component. Types are automatically regenerated during development
 * when files are added or removed.
 *
 * @param userOptions - Configuration options for the plugin
 * @param userOptions.assetsPath - Root directory for assets (default: "public")
 * @param userOptions.outputDir - Base output directory (default: "build")
 * @param userOptions.outputClientDir - Client assets output directory (default: "build/client/assets")
 * @param userOptions.includeDirs - Array of subdirectories to scan for generating types (default: ["images", "themes"])
 * @param userOptions.debug - Enable debug logging (default: false)
 *
 * @returns An array of Vite plugins
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { defineConfig } from "vite";
 * import { generateImagePaths } from "./vite/plugins/vite-plugin-generate-image-paths";
 *
 * export default defineConfig({
 *   plugins: [
 *     generateImagePaths({
 *       assetsPath: "public",
 *       outputDir: "build",
 *       outputClientDir: "build/client/assets",
 *       includeDirs: ["images", "themes"],
 *       debug: true,
 *     }),
 *   ],
 * });
 * ```
 *
 * @example
 * Generated type file structure:
 * ```ts
 * declare global {
 *   export type ImagePath = "images/logo.png" | "images/hero.jpg";
 *   export type ThemePath = "themes/dark.css" | "themes/light.css";
 * }
 * ```
 *
 * @see {@link BBImage}
 */
export function generateImagePaths(
  userOptions: ImagePathPluginOptions = {},
): Plugin[] {
  const options = { ...defaultOptions(), ...userOptions };

  return [
    {
      name: "vite-plugin-generate-image-paths",
      apply: "serve", // Run in dev and build mode
      async buildStart() {
        await generateTypeFile(options);
      },
      async configureServer(server: ViteDevServer) {
        // Generate type file for the first time when server is configured
        await generateTypeFile(options);

        const watchDirs = options.includeDirs.map((d) =>
          path.resolve(process.cwd(), options.assetsPath, d),
        );
        for (const dir of watchDirs) server.watcher.add(dir);

        const isWatchedPath = (filePath: string) =>
          filePath.startsWith(path.resolve(process.cwd(), options.assetsPath));

        // On file additions and deletions, regenerate type file
        server.watcher.on("add", async (file) => {
          if (isWatchedPath(file)) {
            await generateTypeFile(options);
          }
        });

        server.watcher.on("unlink", async (file) => {
          if (isWatchedPath(file)) {
            await generateTypeFile(options);
          }
        });
      },
      async closeBundle() {
        await generateTypeFile(options);
      },
    },
  ];
}
