name: CI
# trigger on changes to package.json, yarn.lock, .nvmrc, or .github/workflows/*.yml or src/**/* files
on:
  pull_request:
    paths:
      - "package.json"
      - "yarn.lock"
      - ".nvmrc"
      - ".github/**/*"
      - "src/**/*"

permissions:
  contents: read

env:
  CI: 1

concurrency:
  group: "${{github.workflow}}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ZFGCCP/github-common/.github/workflows/workflow-reactjs-reusable-build.yml@main
    with:
      environment: ${{ github.head_ref }}

  dependabutt-check:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check if run is triggered by dependabot
        uses: ZFGCCP/github-common/actions/auto-approve-dependabot@main
